"""
This file is automatically generated. Do not modify it manually.
"""

from .base_api_module import BaseApiModule


class AssetTypesApiModule(BaseApiModule):
    def list(self, params=None, **kwargs):
        """
        Returns an array asset types.

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :param dict params: is_active: string
        limit: integer
        name: string
        offset: integer
        ordering: string

        :returns: properties:
          count:
            type: integer
          next:
            format: uri
            nullable: true
            type: string
          previous:
            format: uri
            nullable: true
            type: string
          results:
            items:
              $ref: '#/components/schemas/AssetType'
            type: array
        required:
        - count
        - results
        type: object

        https://docs.huvrdata.app/reference/api_asset-types_list
        """
        return self.client.request_json(
            method="get",
            path=f"/api/asset-types/",
            params=params,
            **kwargs,
        )

    def create(self, json=None, **kwargs):
        """
        Asset Type endpoint


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        :param dict json: $ref: '#/components/requestBodies/AssetType'

        :returns: $ref: '#/components/schemas/AssetType'

        https://docs.huvrdata.app/reference/api_asset-types_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/asset-types/",
            json=json,
            **kwargs,
        )

    def read(self, id, **kwargs):
        """
        Return the specific asset type
        :params id asset ID

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :returns: $ref: '#/components/schemas/AssetType'

        https://docs.huvrdata.app/reference/api_asset-types_read
        """
        return self.client.request_json(
            method="get",
            path=f"/api/asset-types/{id}/",
            **kwargs,
        )

    def update(self, id, json=None, **kwargs):
        """
        AssetType updates

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        :param dict json: $ref: '#/components/requestBodies/AssetType'

        :returns: $ref: '#/components/schemas/AssetType'

        https://docs.huvrdata.app/reference/api_asset-types_update
        """
        return self.client.request_json(
            method="put",
            path=f"/api/asset-types/{id}/",
            json=json,
            **kwargs,
        )

    def partial_update(self, id, json=None, **kwargs):
        """
        Asset Type endpoint


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        :param dict json: $ref: '#/components/requestBodies/AssetType'

        :returns: $ref: '#/components/schemas/AssetType'

        https://docs.huvrdata.app/reference/api_asset-types_partial_update
        """
        return self.client.request_json(
            method="patch",
            path=f"/api/asset-types/{id}/",
            json=json,
            **kwargs,
        )

    def delete(self, id, **kwargs):
        """
        Asset Type endpoint


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        https://docs.huvrdata.app/reference/api_asset-types_delete
        """
        return self.client.request_json(
            method="delete",
            path=f"/api/asset-types/{id}/",
            **kwargs,
        )
