"""
This file is automatically generated. Do not modify it manually.
"""

from .base_api_module import BaseApiModule


class AuthApiModule(BaseApiModule):
    def obtain_access_token_create(self, json=None, **kwargs):
        """
        NOTE - we're using `client_id` and `client_secret`
            standard naming for "OAuth Client Credentials Flow"
            they map internally to service user's `email` and `password`
            https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow

        Return a short-lived Token used for subsequent requests

        Required permissions:
        - WorkspaceRequired
        - AllowAny

        :param dict json: $ref: '#/components/schemas/ObtainAccessTokenRequest'

        :returns: $ref: '#/components/schemas/ObtainAccessTokenResponse'

        https://docs.huvrdata.app/reference/api_auth_obtain-access-token_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/auth/obtain-access-token/",
            json=json,
            **kwargs,
        )

    def revoke_all_create(self, **kwargs):
        """
        Revoke all refresh tokens for the user
        The verify_token or verify_session_cookie will see this change IF they are called with check_revoked=True
        check_revoked requires and extra network call to the Identity Platform so we do not call it all the time

        Required permissions:
        - AllowAny

        https://docs.huvrdata.app/reference/api_auth_revoke-all_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/auth/revoke-all/",
            **kwargs,
        )

    def session_login_create(self, **kwargs):
        """
        Verify JWT from client
         - sets `auth` cookie on response (used for _firebase_ auth)
         - sets `sessionid` cookie on response (used for _django_ auth)

        Required permissions:
        - WorkspaceRequired
        - AllowAny

        https://docs.huvrdata.app/reference/api_auth_session-login_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/auth/session-login/",
            **kwargs,
        )

    def session_logout_create(self, **kwargs):
        """
        Removes session cookie

        Required permissions:
        - AllowAny

        https://docs.huvrdata.app/reference/api_auth_session-logout_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/auth/session-logout/",
            **kwargs,
        )
