"""
This file is automatically generated. Do not modify it manually.
"""

from .base_api_module import BaseApiModule


class DefectProfilesApiModule(BaseApiModule):
    def list(self, params=None, **kwargs):
        """
        Returns an array of defect profiles.

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :param dict params: limit: integer
        offset: integer
        ordering: string

        https://docs.huvrdata.app/reference/api_defect-profiles_list
        """
        return self.client.request_json(
            method="get",
            path=f"/api/defect-profiles/",
            params=params,
            **kwargs,
        )

    def create(self, **kwargs):
        """
        View DefectProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::defect_create

        https://docs.huvrdata.app/reference/api_defect-profiles_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/defect-profiles/",
            **kwargs,
        )

    def import_template(self, json=None, **kwargs):
        """
        Import a defect profile template, currently imports yaml templates.

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::UNDEFINED

        :param dict json: $ref: '#/components/schemas/TemplateImport'

        :returns: $ref: '#/components/schemas/DefectProfile'

        https://docs.huvrdata.app/reference/api_defect-profiles_import_template
        """
        return self.client.request_json(
            method="post",
            path=f"/api/defect-profiles/import-template/",
            json=json,
            **kwargs,
        )

    def read(self, id, **kwargs):
        """
        Return the specific Defect Profile
        :params id

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        https://docs.huvrdata.app/reference/api_defect-profiles_read
        """
        return self.client.request_json(
            method="get",
            path=f"/api/defect-profiles/{id}/",
            **kwargs,
        )

    def update(self, id, **kwargs):
        """
        View DefectProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::defect_edit

        https://docs.huvrdata.app/reference/api_defect-profiles_update
        """
        return self.client.request_json(
            method="put",
            path=f"/api/defect-profiles/{id}/",
            **kwargs,
        )

    def partial_update(self, id, **kwargs):
        """
        View DefectProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::defect_edit

        https://docs.huvrdata.app/reference/api_defect-profiles_partial_update
        """
        return self.client.request_json(
            method="patch",
            path=f"/api/defect-profiles/{id}/",
            **kwargs,
        )

    def delete(self, id, **kwargs):
        """
        View DefectProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::defect_delete

        https://docs.huvrdata.app/reference/api_defect-profiles_delete
        """
        return self.client.request_json(
            method="delete",
            path=f"/api/defect-profiles/{id}/",
            **kwargs,
        )
