"""
This file is automatically generated. Do not modify it manually.
"""

from .base_api_module import BaseApiModule


class LocationLayerProfilesApiModule(BaseApiModule):
    def list(self, params=None, **kwargs):
        """
        Returns an array of LocationLayerProfile.

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :param dict params: limit: integer
        offset: integer
        ordering: string

        https://docs.huvrdata.app/reference/api_location-layer-profiles_list
        """
        return self.client.request_json(
            method="get",
            path=f"/api/location-layer-profiles/",
            params=params,
            **kwargs,
        )

    def create(self, **kwargs):
        """
        View LocationLayerProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        https://docs.huvrdata.app/reference/api_location-layer-profiles_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/location-layer-profiles/",
            **kwargs,
        )

    def import_template(self, json=None, **kwargs):
        """
        Import a Location Layer template, this endpoint can simply do the conversion to yaml
        The `action` parameter switches between import/convert.
        If the `id` is passed in it will attempt to update the exisiting template.

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::UNDEFINED

        :param dict json: $ref: '#/components/schemas/LocationLayerProfile'

        :returns: $ref: '#/components/schemas/LocationLayerProfile'

        https://docs.huvrdata.app/reference/api_location-layer-profiles_import_template
        """
        return self.client.request_json(
            method="post",
            path=f"/api/location-layer-profiles/import-template/",
            json=json,
            **kwargs,
        )

    def read(self, id, **kwargs):
        """
        Return the specific LocationLayerProfile
        :params id

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        https://docs.huvrdata.app/reference/api_location-layer-profiles_read
        """
        return self.client.request_json(
            method="get",
            path=f"/api/location-layer-profiles/{id}/",
            **kwargs,
        )

    def update(self, id, **kwargs):
        """
        View LocationLayerProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        https://docs.huvrdata.app/reference/api_location-layer-profiles_update
        """
        return self.client.request_json(
            method="put",
            path=f"/api/location-layer-profiles/{id}/",
            **kwargs,
        )

    def partial_update(self, id, **kwargs):
        """
        View LocationLayerProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        https://docs.huvrdata.app/reference/api_location-layer-profiles_partial_update
        """
        return self.client.request_json(
            method="patch",
            path=f"/api/location-layer-profiles/{id}/",
            **kwargs,
        )

    def delete(self, id, **kwargs):
        """
        View LocationLayerProfile


        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::configuration_management_build

        https://docs.huvrdata.app/reference/api_location-layer-profiles_delete
        """
        return self.client.request_json(
            method="delete",
            path=f"/api/location-layer-profiles/{id}/",
            **kwargs,
        )
