"""
This file is automatically generated. Do not modify it manually.
"""

from .base_api_module import BaseApiModule


class MeasurementsApiModule(BaseApiModule):
    def list(self, params=None, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :param dict params: cml: string
        cml__name: string
        cml_asset_path: string
        collected_by__name: string
        collected_on: string
        comment: string
        limit: integer
        measurement_offset: string
        offset: integer
        ordering: string
        project: string
        project__name: string
        search: string
        state: string
        type: string
        units: string
        value: string

        :returns: properties:
          count:
            type: integer
          next:
            format: uri
            nullable: true
            type: string
          previous:
            format: uri
            nullable: true
            type: string
          results:
            items:
              $ref: '#/components/schemas/MeasurementList'
            type: array
        required:
        - count
        - results
        type: object

        https://docs.huvrdata.app/reference/api_measurements_list
        """
        return self.client.request_json(
            method="get",
            path=f"/api/measurements/",
            params=params,
            **kwargs,
        )

    def create(self, json=None, **kwargs):
        """
        create Measurement

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::checklist_edit

        :param dict json: $ref: '#/components/requestBodies/MeasurementCreate'

        :returns: $ref: '#/components/schemas/Measurement'

        https://docs.huvrdata.app/reference/api_measurements_create
        """
        return self.client.request_json(
            method="post",
            path=f"/api/measurements/",
            json=json,
            **kwargs,
        )

    def delete(self, json=None, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::UNDEFINED

        :param dict json: $ref: '#/components/schemas/Measurement'

        https://docs.huvrdata.app/reference/api_measurements_delete
        """
        return self.client.request_json(
            method="post",
            path=f"/api/measurements/bulk-delete/",
            json=json,
            **kwargs,
        )

    def import_measurements(self, json=None, **kwargs):
        """
        import measurements
        if asset_path is passed in. We will walk the downtree assets
        looking for matching CML's

        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::checklist_edit

        :param dict json: $ref: '#/components/schemas/MeasurementImport'

        :returns: $ref: '#/components/schemas/Measurement'

        https://docs.huvrdata.app/reference/api_measurements_import_measurements
        """
        return self.client.request_json(
            method="post",
            path=f"/api/measurements/import/",
            json=json,
            **kwargs,
        )

    def read(self, id, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired

        :returns: $ref: '#/components/schemas/Measurement'

        https://docs.huvrdata.app/reference/api_measurements_read
        """
        return self.client.request_json(
            method="get",
            path=f"/api/measurements/{id}/",
            **kwargs,
        )

    def update(self, id, json=None, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::checklist_edit

        :param dict json: $ref: '#/components/requestBodies/MeasurementCreate'

        :returns: $ref: '#/components/schemas/Measurement'

        https://docs.huvrdata.app/reference/api_measurements_update
        """
        return self.client.request_json(
            method="put",
            path=f"/api/measurements/{id}/",
            json=json,
            **kwargs,
        )

    def partial_update(self, id, json=None, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::checklist_edit

        :param dict json: $ref: '#/components/requestBodies/MeasurementCreate'

        :returns: $ref: '#/components/schemas/MeasurementCreate'

        https://docs.huvrdata.app/reference/api_measurements_partial_update
        """
        return self.client.request_json(
            method="patch",
            path=f"/api/measurements/{id}/",
            json=json,
            **kwargs,
        )

    def delete_alt(self, id, **kwargs):
        """
        Required permissions:
        - IsAuthenticated
        - WorkspaceRequired
        - HasRolePermissions::checklist_edit

        https://docs.huvrdata.app/reference/api_measurements_delete_alt
        """
        return self.client.request_json(
            method="delete",
            path=f"/api/measurements/{id}/",
            **kwargs,
        )
